services:
  allmaps-data-export:
    container_name: allmaps-data-export
    build: .
    volumes:
      - ./src:/allmaps/src
      - ./config:/allmaps/config
      - ./data:/allmaps/data
    environment:
      - ALLMAPS_API_KEY=${ALLMAPS_API_KEY}
      - RCLONE_CONFIG_R2_ACCESS_KEY_ID=${RCLONE_CONFIG_R2_ACCESS_KEY_ID}
      - RCLONE_CONFIG_R2_SECRET_ACCESS_KEY=${RCLONE_CONFIG_R2_SECRET_ACCESS_KEY}
    stdin_open: true
    tty: true
